### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by AnonymousRonin** [darkoperator/dnsrecon#269]
This used to work great, now every query I do I get this or something very similar.

 dnsrecon -a -d google.com
[*] std: Performing General Enumeration against: google.com...
Traceback (most recent call last):
  File "/usr/bin/dnsrecon", line 7, in <module>
    __main__.main()
  File "/usr/share/dnsrecon/dnsrecon/cli.py", line 1885, in main
    std_enum_records = general_enum(res, domain, xfr, bing, yandex,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/dnsrecon/dnsrecon/cli.py", line 1137, in general_enum
    check_wildcard(res, domain)
  File "/usr/share/dnsrecon/dnsrecon/cli.py", line 192, in check_wildcard
    ips = res.get_a(testname)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/share/dnsrecon/dnsrecon/lib/dnshelper.py", line 120, in get_a
    answers = self.get_answers('A', host_trg)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/dnsrecon/dnsrecon/lib/dnshelper.py", line 84, in get_answers
    return self._res.resolve(addr_, type_, tcp=self._is_tcp)                                                                                                                                                                                                
           ^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                                
AttributeError: 'Resolver' object has no attribute 'resolve'

**Comment by L1ghtn1ng** [comment]
Will see if I can replicate the issue tomorrow when I am free and go from there

**Comment by L1ghtn1ng** [comment]
what version are you running as I cannot reproduce it at all?

**Comment by AnonymousRonin** [comment]
I'm not sure what the reason is, but it worked fine then I had to download python3.6.  It was working with 3.11.  The version I have now is 1.15.  Not sure which version was the default when I loaded kali's latest version or if it upgraded.

**Comment by AnonymousRonin** [comment]
Works great now!!

ronin@kali:~$ dnsrecon -a -d google.com
[*] std: Performing General Enumeration against: google.com...
[*] Checking for Zone Transfer for google.com name servers
[*] Resolving SOA Record
[+]      SOA ns1.google.com 216.239.32.10
[+]      SOA ns1.google.com 2001:4860:4802:32::a
[*] Resolving NS Records
[*] NS Servers found:
[+]      NS ns4.google.com 216.239.38.10
[+]      NS ns4.google.com 2001:4860:4802:38::a
[+]      NS ns3.google.com 216.239.36.10
[+]      NS ns3.google.com 2001:4860:4802:36::a
[+]      NS ns1.google.com 216.239.32.10
[+]      NS ns1.google.com 2001:4860:4802:32::a
[+]      NS ns2.google.com 216.239.34.10
[+]      NS ns2.google.com 2001:4860:4802:34::a
[*] Removing any duplicate NS server IP Addresses...
[*]                                                                                                                                                                                                                                                         
[*] Trying NS server 2001:4860:4802:36::a                                                                                                                                                                                                                   
[-] Zone Transfer Failed for 2001:4860:4802:36::a!                                                                                                                                                                                                          
[-] Port 53 TCP is being filtered                                                                                                                                                                                                                           
[*]                                                                                                                                                                                                                                                         
[*] Trying NS server 216.239.32.10                                                                                                                                                                                                                          
[+] 216.239.32.10 Has port 53 TCP Open                                                                                                                                                                                                                      
[-] Zone Transfer Failed (No answer or RRset not for qname)                                                                                                                                                                                                 
[*]                                                                                                                                                                                                                                                         
[*] Trying NS server 2001:4860:4802:38::a                                                                                                                                                                                                                   
[-] Zone Transfer Failed for 2001:4860:4802:38::a!                                                                                                                                                                                                          
[-] Port 53 TCP is being filtered                                                                                                                                                                                                                           
[*]                                                                                                                                                                                                                                                         
[*] Trying NS server 216.239.38.10                                                                                                                                                                                                                          
[+] 216.239.38.10 Has port 53 TCP Open                                                                                                                                                                                                                      
[-] Zone Transfer Failed (No answer or RRset not for qname)                                                                                                                                                                                                 
[*]                                                                                                                                                                                                                                                         
[*] Trying NS server 216.239.34.10                                                                                                                                                                                                                          
[+] 216.239.34.10 Has port 53 TCP Open                                                                                                                                                                                                                      
[-] Zone Transfer Failed (No answer or RRset not for qname)                                                                                                                                                                                                 
[*]                                                                                                                                                                                                                                                         
[*] Trying NS server 2001:4860:4802:34::a                                                                                                                                                                                                                   
[-] Zone Transfer Failed for 2001:4860:4802:34::a!                                                                                                                                                                                                          
[-] Port 53 TCP is being filtered                                                                                                                                                                                                                           
[*]                                                                                                                                                                                                                                                         
[*] Trying NS server 2001:4860:4802:32::a                                                                                                                                                                                                                   
[-] Zone Transfer Failed for 2001:4860:4802:32::a!                                                                                                                                                                                                          
[-] Port 53 TCP is being filtered                                                                                                                                                                                                                           
[*]                                                                                                                                                                                                                                                         
[*] Trying NS server 216.239.36.10                                                                                                                                                                                                                          
[+] 216.239.36.10 Has port 53 TCP Open
[-] Zone Transfer Failed (No answer or RRset not for qname)
[*] Checking for Zone Transfer for google.com name servers
[*] Resolving SOA Record
[+]      SOA ns1.google.com 216.239.32.10
[+]      SOA ns1.google.com 2001:4860:4802:32::a
[*] Resolving NS Records
[*] NS Servers found:
[+]      NS ns1.google.com 216.239.32.10
[+]      NS ns1.google.com 2001:4860:4802:32::a
[+]      NS ns2.google.com 216.239.34.10
[+]      NS ns2.google.com 2001:4860:4802:34::a
[+]      NS ns4.google.com 216.239.38.10
[+]      NS ns4.google.com 2001:4860:4802:38::a
[+]      NS ns3.google.com 216.239.36.10
[+]      NS ns3.google.com 2001:4860:4802:36::a
[*] Removing any duplicate NS server IP Addresses...
[*]  
[*] Trying NS server 2001:4860:4802:36::a
[-] Zone Transfer Failed for 2001:4860:4802:36::a!
[-] Port 53 TCP is being filtered
[*]  
[*] Trying NS server 216.239.32.10
[+] 216.239.32.10 Has port 53 TCP Open
[-] Zone Transfer Failed (No answer or RRset not for qname)
[*]  
[*] Trying NS server 2001:4860:4802:38::a
[-] Zone Transfer Failed for 2001:4860:4802:38::a!
[-] Port 53 TCP is being filtered
[*]  
[*] Trying NS server 216.239.38.10
[+] 216.239.38.10 Has port 53 TCP Open
[-] Zone Transfer Failed (No answer or RRset not for qname)
[*]  
[*] Trying NS server 216.239.34.10
[+] 216.239.34.10 Has port 53 TCP Open
[-] Zone Transfer Failed (No answer or RRset not for qname)
[*]  
[*] Trying NS server 2001:4860:4802:34::a
[-] Zone Transfer Failed for 2001:4860:4802:34::a!
[-] Port 53 TCP is being filtered
[*]  
[*] Trying NS server 2001:4860:4802:32::a
[-] Zone Transfer Failed for 2001:4860:4802:32::a!
[-] Port 53 TCP is being filtered
[*]  
[*] Trying NS server 216.239.36.10
[+] 216.239.36.10 Has port 53 TCP Open
[-] Zone Transfer Failed (No answer or RRset not for qname)
[-] DNSSEC is not configured for google.com
[*]      SOA ns1.google.com 216.239.32.10
[*]      SOA ns1.google.com 2001:4860:4802:32::a
[*]      NS ns3.google.com 216.239.36.10
[*]      NS ns3.google.com 2001:4860:4802:36::a
[*]      NS ns1.google.com 216.239.32.10
[*]      NS ns1.google.com 2001:4860:4802:32::a
[*]      NS ns2.google.com 216.239.34.10
[*]      NS ns2.google.com 2001:4860:4802:34::a
[*]      NS ns4.google.com 216.239.38.10
[*]      NS ns4.google.com 2001:4860:4802:38::a
[*]      MX smtp.google.com 74.125.197.27
[*]      MX smtp.google.com 74.125.135.27
[*]      MX smtp.google.com 108.177.98.27
[*]      MX smtp.google.com 108.177.98.26
[*]      MX smtp.google.com 74.125.197.26
[*]      MX smtp.google.com 2607:f8b0:400e:c07::1a
[*]      MX smtp.google.com 2607:f8b0:400e:c07::1b
[*]      MX smtp.google.com 2607:f8b0:400e:c06::1b
[*]      MX smtp.google.com 2607:f8b0:400e:c0d::1b
[*]      A google.com 172.217.14.206
[*]      AAAA google.com 2607:f8b0:400a:800::200e
[*]      TXT google.com docusign=05958488-4752-4ef2-95eb-aa7ba8a3bd0e
[*]      TXT google.com globalsign-smime-dv=CDYX+XFHUw2wml6/Gb8+59BsH31KzUr6c1l2BPvqKX8=
[*]      TXT google.com google-site-verification=TV9-DBe4R80X4v0M4U_bd_J9cpOJM0nikft0jAgjmsQ
[*]      TXT google.com v=spf1 include:_spf.google.com ~all
[*]      TXT google.com docusign=1b0a6754-49b1-4db5-8540-d2c12664b289
[*]      TXT google.com apple-domain-verification=30afIBcvSuDV2PLX
[*]      TXT google.com facebook-domain-verification=22rm551cu4k0ab0bxsw536tlds4h95
[*]      TXT google.com webexdomainverification.8YX6G=6e6922db-e3e6-4a36-904e-a805c28087fa
[*]      TXT google.com google-site-verification=wD8N7i1JTNTkezJ49swvWW48f8_9xveREV4oB-0Hf5o
[*]      TXT google.com onetrust-domain-verification=de01ed21f2fa4d8781cbc3ffb89cf4ef
[*]      TXT google.com MS=E4A68B9AB2BB9670BCE15412F62916164C0B20BB
[*]      TXT _dmarc.google.com v=DMARC1; p=reject; rua=mailto:mailauth-reports@google.com
[*] Enumerating SRV Records
[+]      SRV _ldap._tcp.google.com ldap.google.com 216.239.32.58 389
[+]      SRV _ldap._tcp.google.com ldap.google.com 2001:4860:4802:32::3a 389
[+]      SRV _caldavs._tcp.google.com calendar.google.com 142.251.215.238 443
[+]      SRV _caldavs._tcp.google.com calendar.google.com 2607:f8b0:400a:80b::200e 443
[+]      SRV _carddavs._tcp.google.com google.com 142.251.33.110 443
[+]      SRV _carddavs._tcp.google.com google.com 2607:f8b0:400a:807::200e 443
[+]      SRV _caldav._tcp.google.com calendar.google.com 142.250.217.78 80
[+]      SRV _caldav._tcp.google.com calendar.google.com 2607:f8b0:400a:80b::200e 80
[+] 8 Records Found
